name: 'Blog Custom Github Action'
description: 'Call an API and get the result'
inputs:
  json_value:
    description: 'JSON string whose file path need to be add to cred'
    required: true
    default: ""
  variable_name:
    description: 'Variable name which should be populated with the path name where the json will be stored and added to the github env '
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.json_value }}
    - ${{ inputs.variable_name }}