on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v1
    - name: Get Pokemon name
      uses: actions/actions-custom-test@v1.0.0 # Uses an action in the root directory=
      with:
        json_value: ${{ secrets.TEST_CRED }}
        variable_name: 'NEW_VAR'