on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Get Pokemon name
      uses: ./ # Uses an action in the root directory
      id: pokemon
      with:
        json_value: '{"type":"service_account"}'