on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v1
    - name: Get Pokemon name
      uses: ./ # Uses an action in the root directory=
      
      with:
        json_value: '{"type":"service_account"}'